// Sequelize model: Case
//   id, clientId, professionalId, firmId, title, category, status,
//   description + timestamps
// status: 'open' | 'in-progress' | 'closed'
// Attached files live in the separate `files` table (see File model).

const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');
const jsonField = require('./jsonField');

const genId = () =>
  `case-${Date.now()}-${Math.floor(Math.random() * 10000)}`;

const Case = sequelize.define(
  'Case',
  {
    id: {
      type: DataTypes.STRING(64),
      primaryKey: true,
      allowNull: false,
      defaultValue: genId,
    },
    // Primary client for this case — kept for back-compat with surfaces
    // that expect a single client. New code should read `clientIds` (and
    // the decorated `clients` array on API responses) instead.
    clientId: { type: DataTypes.STRING(64), allowNull: true },
    // Multi-client support — a case may have any number of clients (e.g.
    // joint litigation). Stored as a JSON array of users.id values. The
    // afterFind hook in models/index.js parses it for raw queries.
    clientIds: jsonField('clientIds', []),
    // Primary assignee — back-compat for single-assignee surfaces.
    professionalId: { type: DataTypes.STRING(64), allowNull: true },
    // Multi-assignee support: a case can be assigned to any number of
    // professionals. Stored as a JSON array of public professional ids
    // (legacy `prof-N` OR new `pdetail-...`). The afterFind hook parses
    // this for raw queries; the primary `professionalId` column stays in
    // sync (= professionalIds[0]).
    professionalIds: jsonField('professionalIds', []),
    firmId: { type: DataTypes.STRING(64), allowNull: true },
    title: { type: DataTypes.STRING, allowNull: false, defaultValue: '' },
    category: { type: DataTypes.STRING, allowNull: false, defaultValue: '' },
    status: {
      type: DataTypes.STRING,
      allowNull: false,
      defaultValue: 'open',
    },
    description: { type: DataTypes.TEXT, allowNull: true },
    // Descriptive fields added for the firm case-management module.
    priority: {
      type: DataTypes.STRING(20),
      allowNull: false,
      defaultValue: 'medium',
    },
    caseNumber: { type: DataTypes.STRING, allowNull: true },
    courtName: { type: DataTypes.STRING, allowNull: true },
    opposingParty: { type: DataTypes.STRING, allowNull: true },
    nextHearingDate: { type: DataTypes.DATEONLY, allowNull: true },
    // --- Stage tracking -----------------------------------------------
    // stageType picks a pipeline (civil_suit, criminal_complaint,
    // writ_petition, matrimonial, tax_appeal_cit_a, gst_appeal); stage
    // is the current step within that pipeline. Both NULL on cases
    // that pre-date the feature OR cases where the pro hasn't picked a
    // pipeline yet (rendered as "no stage" in the UI). Source of truth
    // for the value-domain is backend/seeds/compliance-rules.json
    // loaded via config/caseStages.js.
    stageType: { type: DataTypes.STRING(40), allowNull: true },
    stage: { type: DataTypes.STRING(60), allowNull: true },
    stageUpdatedAt: { type: DataTypes.DATE, allowNull: true },
    // Google Calendar event id for the case's NEXT hearing. Recreated
    // on every nextHearingDate change (we delete-then-create rather
    // than patch to keep the upsert logic simple).
    googleHearingEventId: { type: DataTypes.STRING(128), allowNull: true },
    // AI Clerk summary — generated by the per-case AI assistant when
    // the pro presses "Summarize the case". Persisted so subsequent
    // page loads can show the existing summary without re-running
    // the LLM (regenerate is one button click). Visible to client +
    // pro; only the pro can trigger creation/refresh.
    aiSummary: { type: DataTypes.TEXT, allowNull: true },
    aiSummaryUpdatedAt: { type: DataTypes.DATE, allowNull: true },
    aiSummaryByUserId: { type: DataTypes.STRING(64), allowNull: true },
    // Optional: when a firm creates the case it may not yet have a
    // professional assigned. assignedByUserId records who made the assignment.
    assignedByUserId: { type: DataTypes.STRING(64), allowNull: true },
    assignedAt: { type: DataTypes.DATE, allowNull: true },
    // Anchors a case back to the booking that produced it. NULL for cases
    // created manually (firm or admin). Enforced as "one live case per
    // booking" by the convertBookingToCase controller — deleting the case
    // clears the row, so the next conversion is free to create another.
    bookingId: { type: DataTypes.STRING(64), allowNull: true },

    // --- E-Courts India (eci) integration -----------------------------
    // When a case is imported from ecourtsindia.com the columns below are
    // populated from the partner API. `source = 'ecourts'` flags such
    // rows so the dashboard can show the "Update from E-Court" button
    // (which re-fetches and stores a fresh snapshot under `eciSnapshot`).
    // Manual cases keep source = 'manual'.
    source: {
      type: DataTypes.STRING(32),
      allowNull: false,
      defaultValue: 'manual',
    },
    cnr: { type: DataTypes.STRING(32), allowNull: true },
    caseType: { type: DataTypes.STRING(64), allowNull: true },
    courtCode: { type: DataTypes.STRING(64), allowNull: true },
    state: { type: DataTypes.STRING(64), allowNull: true },
    district: { type: DataTypes.STRING(128), allowNull: true },
    filingDate: { type: DataTypes.DATEONLY, allowNull: true },
    decisionDate: { type: DataTypes.DATEONLY, allowNull: true },
    petitioners: jsonField('petitioners', []),
    respondents: jsonField('respondents', []),
    judges: jsonField('judges', []),
    petitionerAdvocates: jsonField('petitionerAdvocates', []),
    respondentAdvocates: jsonField('respondentAdvocates', []),
    actsAndSections: jsonField('actsAndSections', []),
    // Full upstream JSON blob (courtCaseData) from the last sync — used
    // to diff fresh fetches against the stored snapshot so the UI can
    // show "what changed since you last viewed".
    eciSnapshot: { type: DataTypes.JSON, allowNull: true },
    eciSyncedAt: { type: DataTypes.DATE, allowNull: true },
  },
  {
    tableName: 'cases',
    timestamps: true,
    indexes: [
      { fields: ['clientId'] },
      { fields: ['professionalId'] },
      { fields: ['firmId'] },
      { fields: ['status'] },
      { fields: ['category'] },
      // One live case per booking — see convertBookingToCase. Not unique at
      // the DB level (NULL is allowed for cases created without a booking).
      { fields: ['bookingId'] },
      // E-Courts index — a single (userId-scoped) CNR can only be imported
      // once per owner. The duplicate check lives in the import controller
      // (not a DB unique constraint), so this index is just for lookup speed.
      { fields: ['cnr'] },
      { fields: ['source'] },
    ],
  }
);

module.exports = Case;
